# Generated by Django 5.2.7 on 2026-02-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k12auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_accountant',
            new_name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='memberGroupPosition',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
