# Generated by Django 5.2.7 on 2026-02-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k12auth', '0002_rename_is_accountant_user_is_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='memberGroupPosition',
            new_name='membershipTitle',
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
