# Generated by Django 5.2.7 on 2026-03-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k12auth', '0003_rename_membergroupposition_user_membershiptitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.FileField(blank=True, null=True, upload_to='ProfilePictures/'),
        ),
    ]
