# Generated by Django 5.2.7 on 2026-02-26 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberBalance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True)),
                ('troubleFundsBalance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True)),
                ('mainAccountBalance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True)),
                ('donationAccountBalance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Members Account',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True)),
                ('transactionType', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('transactionReference', models.CharField(blank=True, default='0', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
