# Generated by Django 5.2.7 on 2026-02-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='PODs',
            field=models.FileField(blank=True, null=True, upload_to='POD/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactionStatus',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
    ]
