# Generated by Django 5.2.7 on 2026-02-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_transaction_pods_transaction_transactionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
