# Generated by Django 5.2.7 on 2026-03-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donationType',
            field=models.CharField(blank=True, default='0', max_length=250, null=True),
        ),
    ]
