# Generated by Django 5.2.7 on 2026-03-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_donation_donationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donationStatus',
            field=models.CharField(blank=True, default='0', max_length=250, null=True),
        ),
    ]
