# Generated by Django 5.2.7 on 2026-03-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_donation_totaldonationamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='minDonationAmoun',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True),
        ),
    ]
