# Generated by Django 5.2.7 on 2026-03-02 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_donation_mindonationamoun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='minDonationAmoun',
            new_name='minDonationAmount',
        ),
    ]
