# Generated by Django 5.2.7 on 2026-03-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_donationtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationtransaction',
            name='donationStatus',
            field=models.CharField(blank=True, default='0', max_length=250, null=True),
        ),
    ]
