# Generated by Django 5.2.7 on 2026-03-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_donationtransaction_donationstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='donationAccountBalance',
            new_name='registrationAmount',
        ),
    ]
