# Generated by Django 5.2.7 on 2026-03-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_preferencedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencedate',
            name='preference_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
