# Generated by Django 5.2.7 on 2026-03-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_donationwithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationwithdrawal',
            name='PODs',
            field=models.FileField(blank=True, null=True, upload_to='Donations/'),
        ),
    ]
