# Generated by Django 5.2.7 on 2026-03-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='transactionType',
            field=models.CharField(blank=True, default='0', max_length=250, null=True),
        ),
    ]
