# Generated by Django 5.2.7 on 2026-03-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_withdrawal_transactiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='transactionType',
            field=models.CharField(blank=True, default='Withdrawal', max_length=250, null=True),
        ),
    ]
